#ifndef EMBEDDED_CA_H
#define EMBEDDED_CA_H

/*
 * Generated by scripts/generate_certs.sh.
 * This placeholder lets the project compile before the first generation.
 */
static const char EMBEDDED_CA_PEM[] = "";

#endif
